---
local_release_dir: /tmp

# Versions
kube_version: v1.2.2
etcd_version: v2.2.5
calico_version: v0.19.0
calico_cni_version: v1.2.1
weave_version: v1.5.0
romana_version: v0.8.2

# Download URL's
kubelet_download_url: "https://storage.googleapis.com/kargo/{{kube_version}}_kubernetes-kubelet"
apiserver_download_url: "https://storage.googleapis.com/kargo/{{kube_version}}_kubernetes-apiserver"
kubectl_download_url: "https://storage.googleapis.com/kargo/{{kube_version}}_kubernetes-kubectl"
etcd_download_url: "https://storage.googleapis.com/kargo/{{etcd_version}}_etcd"
calico_download_url: "https://storage.googleapis.com/kargo/{{calico_version}}_calico"
calico_cni_download_url: "https://storage.googleapis.com/kargo/{{calico_cni_version}}_calico-cni-plugin"
calico_cni_ipam_download_url: "https://storage.googleapis.com/kargo/{{calico_cni_version}}_calico-cni-plugin-ipam"
weave_download_url: "https://storage.googleapis.com/kargo/{{weave_version}}_weave"
# Changed temporariliy. These should be replaed with kargo uploads
romana_download_url: "https://s3-us-west-1.amazonaws.com/romana-binaries/core/latest/origin/{{ romana_version }}/romana"
romana_cni_download_url: "https://raw.githubusercontent.com/romana/kube/{{ romana_version }}/CNI/romana"
romana_kube_agent_download_url: "https://raw.githubusercontent.com/romana/kube/{{ romana_version }}/NetworkPolicy/k8s-listener.py"
romana_kube_np_download_url: "https://raw.githubusercontent.com/romana/kube/{{ romana_version }}/NetworkPolicy/k8s-listener.py"
romana_agent_download_url: "https://s3-us-west-1.amazonaws.com/romana-binaries/core/latest/origin/{{ romana_version }}/agent"
romana_topology_download_url: "https://s3-us-west-1.amazonaws.com/romana-binaries/core/latest/origin/{{ romana_version }}/topology"
romana_root_download_url: "https://s3-us-west-1.amazonaws.com/romana-binaries/core/latest/origin/{{ romana_version }}/root"
romana_tenant_download_url: "https://s3-us-west-1.amazonaws.com/romana-binaries/core/latest/origin/{{ romana_version }}/tenant"
romana_ipam_download_url: "https://s3-us-west-1.amazonaws.com/romana-binaries/core/latest/origin/{{ romana_version }}/ipam"
romana_nsenter_download_url: "https://s3-us-west-1.amazonaws.com/romana-binaries/external/nsenter"

# Checksums
calico_checksum: "6db00c94619e82d878d348c4e1791f8d2f0db59075f6c8e430fefae297c54d96"
calico_cni_checksum: "b2eeb45fdfce58394e3a0019dd4b74bebe4bb35ed6d7c399213297594f25e89e"
calico_cni_ipam_checksum: "fd122bee97af3ed86fc18fa4d797da29be3a5857a526aa154b433e50d7b36845"
weave_checksum: "28d2c4e2b1ad8600da69882501eba697679aea10a5e61c769aa3a9ee72b0d89a"
etcd_checksum: "aa6037406257d2a1bc48ffa769afe7a4f8a04cc1ffcd36ef84f9ee8bc4eca756"
kubectl_checksum: "473e6924569fba30d4a50cecdc2cae5f31d97d1f662463e85b74a472105dcff4"
kubelet_checksum: "f16827dc7e7c82f0e215f0fc73eb01e2dfe91a2ec83f9cbcaf8d37c91b64fd3b"
kube_apiserver_checksum: "eb1bfd8b877052cbd1991b8c429a1d06661f4cb019905e20e128174f724e16de"
romana_checksum: "053d24f1a3f5cc6b85ff79accf1f43144bdff9b57029d8b9114c83630a408d5d"
romana_agent_checksum: "1fe3f815960a1cd4012cbcdb266f3e1c1cc0f8a5d31229c3917842f8e942500b"
romana_topology_checksum: "a5e57c434b08e497655cc0344f117dae28849ea741b06b36bb27dd435cc4ba39"
romana_root_checksum: "9b87f3d422a61e147c2ce598835e52f2d97ec2c9505a75d029359e053cd4be89"
romana_ipam_checksum: "546bb13ca87bdca1cb65806732f7e04706e32dd264c97ae9824190f39c5c880b"
romana_tenant_checksum: "ab7212a604487c3af4b1a35e661274560e4232415c958bea411e9c1a4055eabf"
romana_cni_checksum: "7f37994af4347e7854a00ba955129b27966e7c859aa81487ca3e439f218532c7"
romana_kube_agent_checksum: "a20bb296ecd0ce5fe2ad0c4ef7c3be49211c5d96c15826bc847d98670027a0be"
romana_kube_np_checksum: "a20bb296ecd0ce5fe2ad0c4ef7c3be49211c5d96c15826bc847d98670027a0be"
romana_nsenter_checksum: "2c14052cacad0b4beddd1f5a12b3cac8ac50c85f96a7d6640ad00a260f98442e"

downloads:
  - name: romana
    dest: romana/bin/romana
    version: "{{romana_version}}"
    sha256: "{{ romana_checksum }}"
    source_url: "{{ romana_download_url }}"
    url: "{{ romana_download_url }}"
    owner: "root"
    mode: "0755"

  - name: romana-cni
    dest: romana/bin/romana-cni
    version: "{{romana_version}}"
    sha256: "{{ romana_cni_checksum }}"
    source_url: "{{ romana_cni_download_url }}"
    url: "{{ romana_cni_download_url }}"
    owner: "root"
    mode: "0755"

  - name: romana-kube-agent
    dest: romana/bin/romana-kube-agent
    version: "{{romana_version}}"
    sha256: "{{ romana_kube_agent_checksum }}"
    source_url: "{{ romana_kube_agent_download_url }}"
    url: "{{ romana_kube_agent_download_url }}"
    owner: "root"
    mode: "0755"

  - name: romana-kube-np
    dest: romana/bin/romana-kube-np
    version: "{{romana_version}}"
    sha256: "{{ romana_kube_np_checksum }}"
    source_url: "{{ romana_kube_np_download_url }}"
    url: "{{ romana_kube_np_download_url }}"
    owner: "root"
    mode: "0755"

  - name: romana-agent
    dest: romana/bin/romana-agent
    version: "{{romana_version}}"
    sha256: "{{ romana_agent_checksum }}"
    source_url: "{{ romana_agent_download_url }}"
    url: "{{ romana_agent_download_url }}"
    owner: "root"
    mode: "0755"

  - name: romana-topology
    dest: romana/bin/romana-topology
    version: "{{romana_version}}"
    sha256: "{{ romana_topology_checksum }}"
    source_url: "{{ romana_topology_download_url }}"
    url: "{{ romana_topology_download_url }}"
    owner: "root"
    mode: "0755"

  - name: romana-root
    dest: romana/bin/romana-root
    version: "{{romana_version}}"
    sha256: "{{ romana_root_checksum }}"
    source_url: "{{ romana_root_download_url }}"
    url: "{{ romana_root_download_url }}"
    owner: "root"
    mode: "0755"

  - name: romana-ipam
    dest: romana/bin/romana-ipam
    version: "{{romana_version}}"
    sha256: "{{ romana_ipam_checksum }}"
    source_url: "{{ romana_ipam_download_url }}"
    url: "{{ romana_ipam_download_url }}"
    owner: "root"
    mode: "0755"

  - name: romana-tenant
    dest: romana/bin/romana-tenant
    version: "{{romana_version}}"
    sha256: "{{ romana_tenant_checksum }}"
    source_url: "{{ romana_tenant_download_url }}"
    url: "{{ romana_tenant_download_url }}"
    owner: "root"
    mode: "0755"

  - name: romana-nsenter
    dest: romana/bin/romana-nsenter
    version: "{{romana_version}}"
    sha256: "{{ romana_nsenter_checksum }}"
    source_url: "{{ romana_nsenter_download_url }}"
    url: "{{ romana_nsenter_download_url }}"
    owner: "root"
    mode: "0755"

  - name: calico
    dest: calico/bin/calicoctl
    version: "{{calico_version}}"
    sha256: "{{ calico_checksum }}"
    source_url: "{{ calico_download_url }}"
    url: "{{ calico_download_url }}"
    owner: "root"
    mode: "0755"

  - name: calico-cni-plugin
    dest: calico/bin/calico
    version: "{{calico_cni_version}}"
    sha256: "{{ calico_cni_checksum }}"
    source_url: "{{ calico_cni_download_url }}"
    url: "{{ calico_cni_download_url }}"
    owner: "root"
    mode: "0755"

  - name: calico-cni-plugin-ipam
    dest: calico/bin/calico-ipam
    version: "{{calico_cni_version}}"
    sha256: "{{ calico_cni_ipam_checksum }}"
    source_url: "{{ calico_cni_ipam_download_url }}"
    url: "{{ calico_cni_ipam_download_url }}"
    owner: "root"
    mode: "0755"

  - name: weave
    dest: weave/bin/weave
    version: "{{weave_version}}"
    source_url: "{{weave_download_url}}"
    url: "{{weave_download_url}}"
    sha256: "{{ weave_checksum }}"
    owner: "root"
    mode: "0755"

  - name: etcd
    version: "{{etcd_version}}"
    dest: "etcd/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    sha256: "{{ etcd_checksum }}"
    source_url: "{{ etcd_download_url }}"
    url: "{{ etcd_download_url }}"
    unarchive: true
    owner: "etcd"
    mode: "0755"

  - name: kubernetes-kubelet
    version: "{{kube_version}}"
    dest: kubernetes/bin/kubelet
    sha256: "{{kubelet_checksum}}"
    source_url: "{{ kubelet_download_url }}"
    url: "{{ kubelet_download_url }}"
    owner: "kube"
    mode: "0755"

  - name: kubernetes-kubectl
    dest: kubernetes/bin/kubectl
    version: "{{kube_version}}"
    sha256: "{{kubectl_checksum}}"
    source_url: "{{ kubectl_download_url }}"
    url: "{{ kubectl_download_url }}"
    owner: "kube"
    mode: "0755"

  - name: kubernetes-apiserver
    dest: kubernetes/bin/kube-apiserver
    version: "{{kube_version}}"
    sha256: "{{kube_apiserver_checksum}}"
    source_url: "{{ apiserver_download_url }}"
    url: "{{ apiserver_download_url }}"
    owner: "kube"
    mode: "0755"
